version: '3'
services:
  upload:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /tmp:/tmp
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: bin/app.py
    command: flask run --host=0.0.0.0
